---
- hosts: 172.31.37.106
  become: yes
  tasks:
  - include_tasks: files.yml
  - name: create a directory
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: i want to copy files
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytestyml.txt

  - name: install apache2
    apt:
     name: apache2
     state: present

  
