---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: I want to install webserver httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start web server on Amazon linux mac
    service:  
      name: https
      state: started
    when: ansible_os_family =="RedHat"