---
- hosts: 172.31.37.22
  become: yes
  tasks:
  - name: install wget
    yum:
     name: wget
     state: present
    tags: mywget

  - name: install tree
    yum: 
     name: tree
     state: present
    tags: mylovelytree 