---
- hosts: 172.31.37.106
  become: yes
  tasks:
  - name: install wget
    apt:
     name: wget
     state: present
    tags: mywget

  - name: install tree
    apt: 
     name: tree
     state: present
    tags:  mylovelytree